name: Run tests

on: [push, pull_request]

jobs:
  cbctests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      # - uses: mxschmitt/action-tmate@v3  # for interactive debugging
      - uses: julia-actions/julia-runtest@latest

  xpresstests:
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v2
        - name: Decrypt
          env:
            TRANSCRYPT_PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
          run: ./.github/scripts/decrypt.sh 
        - name: Build containers and run tests
          run: docker-compose up